---
name: build dev branch

on:
  push:
    branches:
      - 'dev'
    tags-ignore:
      - '**'

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      maven_repo_id: 'repo-id'
      post_sonarqube: 'false'
      push: 'true'
      docker_registry: harbor-ailabs.exus.co.uk
      additional_tag: 'dev'
    secrets:
      maven_username: ${{ secrets.NEXUS_USERNAME }}
      maven_password: ${{ secrets.NEXUS_PASSWORD }}
      docker_registry_username: ${{ secrets.HARBOR_USERNAME }}
      docker_registry_password: ${{ secrets.HARBOR_PASSWORD }}
